'use strict'

module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert('cars', [
      {
        model: 'Honda Civic',
        year: '2019',
        capaciteEngine: '2.0',
        regVihicleNumber: 'HS-820 380',
        technicalPassNumber: 'CXA 003854',
        viaNumber: 'GTRFG43434343243BB4344',
        driveTrain: 'plug-in four-wheel drive',
        fullNameOwner: 'Anton Shpyhunov',
        User_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        model: 'Skoda octavia A5',
        year: '2015',
        capaciteEngine: '2.5',
        regVihicleNumber: 'HS-370 880',
        technicalPassNumber: 'CXA 002154',
        viaNumber: 'GTRFG4342415243BB4344',
        driveTrain: 'plug-in four-wheel drive',
        fullNameOwner: 'Anton Shpyhunov',
        User_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        model: 'Niassan GTR',
        year: '2011',
        capaciteEngine: '3.0',
        regVihicleNumber: 'HS-641 241',
        technicalPassNumber: 'CXA 010554',
        viaNumber: 'GTRFG45HH425243BB4344',
        driveTrain: 'plug-in four-wheel drive',
        fullNameOwner: 'Anton Shpyhunov',
        User_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        model: 'BMW X5',
        year: '2014',
        capaciteEngine: '2.5',
        regVihicleNumber: 'HS-912 231',
        technicalPassNumber: 'CXA 009361',
        viaNumber: 'GTRFG43544343243AA2144',
        driveTrain: 'plug-in four-wheel drive',
        fullNameOwner: 'Semen Struchev',
        User_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        model: 'Shkoda Octavia',
        year: '2012',
        capaciteEngine: '2.5',
        regVihicleNumber: 'HS-912 231',
        technicalPassNumber: 'CXA 009361',
        viaNumber: 'GTRFG43544343243AA2144',
        driveTrain: 'plug-in four-wheel drive',
        fullNameOwner: 'Sierra Ferguson',
        User_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        model: 'Ford Focus',
        year: '2016',
        capaciteEngine: '1.5',
        regVihicleNumber: 'HS-541 241',
        technicalPassNumber: 'CXA 152061',
        viaNumber: 'GTRFG4354434RR2132144',
        driveTrain: 'plug-in four-wheel drive',
        fullNameOwner: 'Adam Johnson',
        User_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ])
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete('cars', null, {})
  },
}
